name: Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - run: npm install
      - name: Build Gatsby Site
        uses: jzweifel/gatsby-cli-github-action@master
        with:
          gatsby-arg: build
      - name: Deploy
        uses: docker://peaceiris/gh-pages:v2.5.0
        env:
          PUBLISH_DIR: public
          PUBLISH_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
